# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7c13398b5bfcdddb7a2521305c261f71968f3e881c8b8e53ce9ae02f6c698552a2b76a51bb8edfbbc7435ce435076561f32657d99c91fbeb8f0370ada30a3cf

test:
  secret_key_base: 6ca6ebdfef102eb36f91b1840cbd16c3c556ac80cce7ae48f222bfaa0271f2c04f246bf287e8a4ebf1ed50ef915bb6ee2c00af7e0186fc70f56f7ee0bc562a6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
